chore: workflows 파일들 수정 - ai-pr-reviewer.yml, firebase-hosting-pull-request.yml 파일 수정 - PR 코맨트로 타입스크립트 에러를 확인 할 수 있게함. - PR 코멘트로 배포 결과를 확인 할 수 있게함

diff --git a/.github/workflows/ai-pr-reviewer.yml b/.github/workflows/ai-pr-reviewer.yml
--- a/.github/workflows/ai-pr-reviewer.yml
+++ b/.github/workflows/ai-pr-reviewer.yml
@@ -20,6 +20,16 @@ jobs:
   review:
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/checkout@v4
+      - uses: oven-sh/setup-bun@v1
+      - run: bun install
+      - name: Compile TypeScript
+        run: |
+          tsc -b
+          if [ $? -ne 0 ]; then
+            echo "TypeScript compilation failed with errors."
+            exit 1
+          fi
       - uses: coderabbitai/ai-pr-reviewer@latest
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -31,6 +41,3 @@ jobs:
           openai_light_model: gpt-3.5-turbo
           openai_heavy_model: gpt-3.5-turbo
           language: ko-KR
-          
-        
-          
